//
//  globalData.swift
//  My PocketUI
//
//  Created by Luca Hummel on 20/07/21.
//

import Foundation

//var contentItems: [[[String]]] = [["Swift"], [["Navigation Bars"], ["Search Bars"], ["Sidebars"], ["Status Bars"], ["Tab Bars"], ["Toolbars"]], [["Action Sheets"], ["Activity Views"], ["Alerts"], ["Collections"], ["Image Views"], ["Pages"], ["Popovers"], ["Scroll Views"], ["Split Views"], ["Tables"], ["Text Views"], ["Web Views"]], [["Buttons"], ["Color Wells"], ["Context Menus"], ["Edit Menus"], ["Labels"], ["Page Controls"], ["Pickers"], ["Progress Indicators"], ["Pull-Down Menus"], ["Refresh Content Controls"], ["Segmented Controls"], ["Sliders"], ["Steppers"], ["Switches"], ["Text Fields"]], ["Pessoal"]]

var barsContents: [Content] = [Content.init(name: "Navigation Bars" ,listContent: [Documentation.init(title: "Navigation Bars", information: "Bom dia tudo bem sssssssssdsdsfhsdjfhsdjhfsjfsjhfjshfshfskhf\n*||*var x = 9\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD\nD")]), Content.init(name: "Search Bars" ,listContent: [Documentation.init(title: "Search Bars")]), Content.init(name: "Sidebars" ,listContent: [Documentation.init(title: "Sidebars")]), Content.init(name: "Status Bars" ,listContent: [Documentation.init(title: "Status Bars")]), Content.init(name: "Tab Bars" ,listContent: [Documentation.init(title: "Tab Bars")]), Content.init(name: "Tool Bars" ,listContent: [Documentation.init(title: "Tool Bars")])]

var viewsContents: [Content] = [Content.init(name: "Action Sheets" ,listContent: [Documentation.init(title: "Action Sheets", information: "")]), Content.init(name: "Activity Views" ,listContent: [Documentation.init(title: "Activity Views")]), Content.init(name: "Alerts" ,listContent: [Documentation.init(title: "Alerts")]), Content.init(name: "Collections" ,listContent: [Documentation.init(title: "Collections")]), Content.init(name: "Image Views" ,listContent: [Documentation.init(title: "Image Views")]), Content.init(name: "Pages" ,listContent: [Documentation.init(title: "Pages")]), Content.init(name: "Popovers" ,listContent: [Documentation.init(title: "Popovers")]), Content.init(name: "Scroll Views" ,listContent: [Documentation.init(title: "Scroll Views")]), Content.init(name: "Split Views" ,listContent: [Documentation.init(title: "Split Views")]), Content.init(name: "Tables" ,listContent: [Documentation.init(title: "Tables")]), Content.init(name: "Text Views" ,listContent: [Documentation.init(title: "Text Views")]), Content.init(name: "Web Views" ,listContent: [Documentation.init(title: "Web Views")])]

var controlsContent: [Content] = [Content.init(name: "Buttons" ,listContent: [Documentation.init(title: "Buttons")]), Content.init(name: "Color Wells" ,listContent: [Documentation.init(title: "Color Wells")]), Content.init(name: "Context Menus" ,listContent: [Documentation.init(title: "Context Menus")]), Content.init(name: "Edit Menus" ,listContent: [Documentation.init(title: "Edit Menus")]), Content.init(name: "Labels" ,listContent: [Documentation.init(title: "Labels")]), Content.init(name: "Page Controls" ,listContent: [Documentation.init(title: "Page Controls")]), Content.init(name: "Pickers" ,listContent: [Documentation.init(title: "Pickers")]), Content.init(name: "Progress Indicators" ,listContent: [Documentation.init(title: "Progress Indicators")]), Content.init(name: "Pull-Down Menus" ,listContent: [Documentation.init(title: "Pull-Down Menus")]), Content.init(name: "Refresh Content Controls" ,listContent: [Documentation.init(title: "Refresh Content Controls")]), Content.init(name: "Segmented Controls" ,listContent: [Documentation.init(title: "Segmented Controls")]), Content.init(name: "Sliders" ,listContent: [Documentation.init(title: "Sliders")]), Content.init(name: "Steppers" ,listContent: [Documentation.init(title: "Steppers")]),  Content.init(name: "Switches" ,listContent: [Documentation.init(title: "Switches")]), Content.init(name: "Text Fields" ,listContent: [Documentation.init(title: "Text Fields")])]

var swiftContents: [Content] = [Content.init(name: "Swift" ,listContent: [Documentation.init(title: "Bom dia"), Documentation.init(title: "Tudo bem")])]


var globalSearch =  [Topic.init(contents: barsContents), Topic.init(contents: viewsContents), Topic.init(contents: controlsContent), Topic.init(contents: swiftContents), Topic.init(contents: pessoalContents)]
